    DROP DATABASE NOME_DATABASE;
CREATE DATABASE IF NOT EXISTS NOME_DATABASE;

USE NOME_DATABASE;

CREATE TABLE IF NOT EXISTS MEDICO(
	ID_MEDICO INT(11) PRIMARY KEY,
    CRM INT(11) NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(20) NOT NULL,
    ESPECIALIDADES VARCHAR(50) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    ENDEREÇO VARCHAR(200) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL);
    
CREATE TABLE IF NOT EXISTS CARGO(
	ID_CARGO INT(11) PRIMARY KEY auto_increment,
    NOME VARCHAR(45));
    
CREATE TABLE IF NOT EXISTS TIPO_EXAME(
    ID_TIPO_EXAME INT(11) PRIMARY KEY,
    TIPO VARCHAR(50) NOT NULL);
    
CREATE TABLE IF NOT EXISTS RESULTADO_EXAME(
	ID_TIPO_RESULTADO_EXAME INT(11) PRIMARY KEY,
    TIPO VARCHAR(30) NOT NULL);
    
CREATE TABLE IF NOT EXISTS RISCOS_OCUPACIONAIS(
	ID_RISCOS INT(11) PRIMARY KEY,
    NOME VARCHAR(45) NOT NULL);
    
CREATE TABLE IF NOT EXISTS EMPRESA(
	ID_EMPRESA INT(11) PRIMARY KEY,
	CNPJ VARCHAR(20) NOT NULL,
	NOME_FANTASIA VARCHAR(50) NOT NULL,
	ENDEREÇO VARCHAR(200) NOT NULL,
	TELEFONE VARCHAR(20) NOT NULL,
    EMPRESA_ID INT(11) NOT NULL,
	CONSTRAINT FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA(ID_EMPRESA));
    
CREATE TABLE IF NOT EXISTS ATESTADO(
	ID_ATESTADO INT(11) PRIMARY KEY,
    RESULTADOS_RISCOS VARCHAR(100) NOT NULL,
    RESULTADO VARCHAR(100) NOT NULL,
    OBSERVAÇOES VARCHAR(300) NOT NULL,
    ID_MEDICO INT(11) NOT NULL,
    CONSTRAINT FOREIGN KEY (ID_MEDICO) REFERENCES MEDICO(ID_MEDICO));
    
CREATE TABLE IF NOT EXISTS FUNCIONARIO(
	ID_FUNCIONARIO INT(11) PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
    CPF VARCHAR(20) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    ENDEREÇO VARCHAR(200) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL,
    ID_CARGO INT(11) NOT NULL,
    ID_EMPRESA INT(11) NOT NULL,
    CONSTRAINT FOREIGN KEY (ID_CARGO) REFERENCES CARGO(ID_CARGO),
	CONSTRAINT FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA(ID_EMPRESA));
    
CREATE TABLE IF NOT EXISTS EXAME(
	ID_EXAME INT(11) PRIMARY KEY,
    ESPECIALIDADE VARCHAR(50) NOT NULL,
    DATA_REALIZAÇAO DATE NOT NULL,
    ID_TIPO_EXAME INT(11) NOT NULL,
    RESULTADO_ID_EXAME INT(11) NOT NULL,
    CONSTRAINT FOREIGN KEY (ID_TIPO_EXAME) REFERENCES TIPO_EXAME(ID_TIPO_EXAME),
    CONSTRAINT FOREIGN KEY (RESULTADO_ID_EXAME) REFERENCES RESULTADO_EXAME(ID_TIPO_RESULTADO_EXAME));
    
CREATE TABLE IF NOT EXISTS EMPRESA_HAS_EXAME(
	ID_EXAME INT(11) NOT NULL,
    ID_EMPRESA INT(11) NOT NULL,
	CONSTRAINT FOREIGN KEY (ID_EXAME) REFERENCES EXAME(ID_EXAME),
    CONSTRAINT FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA(ID_EMPRESA));

CREATE TABLE IF NOT EXISTS FUNCIONARIO_HAS_EXAMES(
	ID_EXAME INT(11) NOT NULL,
    ID_FUNCIONARIO INT(11) NOT NULL,
    CONSTRAINT FOREIGN KEY (ID_EXAME) REFERENCES EXAME(ID_EXAME),
	CONSTRAINT FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIO(ID_FUNCIONARIO));
    
CREATE TABLE IF NOT EXISTS CARGO_HAS_RISCOS_OCUPACIONAIS(
	ID_CARGO INT(11) NOT NULL,
    ID_RISCOS INT(11) NOT NULL,
	CONSTRAINT FOREIGN KEY (ID_CARGO) REFERENCES CARGO(ID_CARGO),
    CONSTRAINT FOREIGN KEY (ID_RISCOS) REFERENCES RISCOS_OCUPACIONAIS(ID_RISCOS));
    
CREATE TABLE IF NOT EXISTS EXAME_HAS_ATESTADO(
	ID_EXAME INT(11) NOT NULL,
    ID_ATESTADO INT(11) NOT NULL,
	CONSTRAINT FOREIGN KEY (ID_EXAME) REFERENCES EXAME(ID_EXAME),
    CONSTRAINT FOREIGN KEY (ID_ATESTADO) REFERENCES ATESTADO(ID_ATESTADO));
    
    


    

    

    

    

    

    

    

    

    


    
    
